version: '3.4'

services:
  appdb:
    container_name: appdb
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    volumes:
      - appdb-data:/var/lib/postgresql/data

  redis-db:
    restart: always
    image: redis
    container_name: redis-db
    ports:
      - 6379:6379
    volumes:
      - "redis-db-data:/data"

  pgadmin:
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root

  app.api:
    restart: always
    depends_on:
      - appdb
    container_name: app.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DB=Host=appdb:5432;Database=bookconnect_db;Username=admin;Password=root"
    ports:
      - "8001:80"
